
set +h
umask 022

LFS=/mnt/lfs
export LFS

SOURCEDIR=$LFS/sources
export SOURCEDIR

BUILDTOP=$LFS/build_tools
export BUILDTOP

LC_ALL=POSIX
export LC_ALL

LFS_TGT=$(uname -m)-lfs-linux-gnu
export LFS_TGT

PATH=/tools/bin:/bin:/usr/bin
export PATH

MAKEFLAGS='-j 4'
export MAKEFLAGS

